name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  # Main comprehensive metrics
  github-metrics-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna  # Replace with your GitHub username
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Languages (basic)
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          
          # Lines of code
          plugin_lines: yes
          plugin_lines_sections: base
          
          # Recent activity
          plugin_activity: yes
          plugin_activity_limit: 5
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          # Recently starred
          plugin_stars: yes
          plugin_stars_limit: 4

  # Detailed languages analysis
  github-metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna  # Replace with your GitHub username
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14

  # Activity and coding habits
  github-metrics-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna  # Replace with your GitHub username
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 14
          plugin_activity_filter: all

  # Detailed achievements
  github-metrics-achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna  # Replace with your GitHub username
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C