name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  # Main comprehensive metrics
  github-metrics-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_stars: yes
          plugin_stars_limit: 4

  # Detailed languages analysis
  github-metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14

  # Activity and coding habits
  github-metrics-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 14
          plugin_activity_filter: all

  # Achievements
  github-metrics-achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

  # Calendar
  github-metrics-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

  # Recently starred repositories
  github-metrics-stars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 4

  # Lines of code
  github-metrics-lines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: repositories, history

  # Topics
  github-metrics-topics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred

  # Follow-up issues and PRs
  github-metrics-followup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

  # Gists
  github-metrics-gists:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: markobonna/metrics@latest
        with:
          filename: metrics.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_gists: yes