name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  # Core
  github-metrics-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          template: classic
          base: activity, community, repositories
          base_indepth: yes
          config_octicon: yes
          config_timezone: America/Los_Angeles
          config_twemoji: yes
          plugin_lines: yes
          plugin_lines_history_limit: 5
          plugin_lines_repositories_limit: 900
          plugin_lines_sections: base
          plugin_traffic: yes
          repositories_forks: yes

  # Lines of code changed
  github-metrics-lines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 900
          plugin_lines_sections: repositories, history

  # Language Activity
  github-metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14

  # Recent Activity
  github-metrics-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 90
          plugin_activity_filter: all
          plugin_activity_load: 300
          plugin_activity_visibility: all

  # Coding habits and Activity
  github-metrics-habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 90
          plugin_habits_from: 900
          plugin_habits_languages_limit: 5
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes

  # Achievements
  github-metrics-achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X

  # Calendar
  github-metrics-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 1

  # ISO Calendar
  github-metrics-isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  # Follow-up issues and Pull Requests
  github-metrics-followup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories

  # Stargazers
  github-metrics-stargazers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 90
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_sample: 110

  # Comment reactions
  github-metrics-comments:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_reactions: yes
          plugin_reactions_display: relative
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100

  # People
  github-metrics-people:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.people.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: markobonna
          base: ""
          plugin_people: yes
          plugin_people_identicons_hide: yes
          plugin_people_limit: 28
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
