name: GitHub Metrics Generator
on:
  # Schedule daily updates at 00:00 UTC
  schedule: [{cron: '0 0 * * *'}]
  # Manual trigger
  workflow_dispatch:
  # Run on push to main/master
  push: {branches: [main, master]}

jobs:
  github-metrics:
    name: Generate GitHub Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Authentication
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          
          # Base configuration
          base: header, repositories, activity, community
          base_indepth: yes
          
          # Core metrics
          plugin_achievements: yes
          plugin_achievements_threshold: B
          
          # Activity metrics
          plugin_activity: yes
          plugin_activity_limit: 15
          plugin_activity_days: 60
          plugin_activity_filter: all
          
          # Code analysis
          plugin_code: yes
          plugin_code_lines: 3
          
          # Calendar and habits
          plugin_calendar: yes
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_from: 100
          plugin_habits_facts: yes
          plugin_habits_days: 90
          
          # Follow-up and collaboration
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_contributors: yes
          
          # People and social
          plugin_people: yes
          plugin_people_limit: 15
          
          # Repository metrics
          plugin_repositories: yes
          plugin_repositories_affiliations: owner,collaborator,organization_member
          plugin_repositories_forks: yes
          
          # Code and languages
          plugin_languages: yes
          plugin_languages_ignored: html,css,less,scss,sass,markdown,dockerfile,makefile,yaml,json,toml,svg
          plugin_languages_skipped: _test_,tests,node_modules,dist,build,out
          plugin_languages_indepth: yes
          plugin_languages_details: lines,bytes-size,percentage
          
          # Stars and stargazers
          plugin_stars: yes
          plugin_stars_limit: 15
          plugin_stargazers: yes
          plugin_starlists: yes
          
          # Topics and interests
          plugin_topics: yes
          plugin_topics_limit: 20
          plugin_topics_mode: starred
          
          # Sponsors and funding
          plugin_sponsors: yes
          plugin_sponsorships: yes
          
          # Discussions
          plugin_discussions: yes
          
          # Gists
          plugin_gists: yes
          
          # Projects
          plugin_projects: yes
          plugin_projects_limit: 10
          
          # Output configuration
          filename: metrics.base.svg
          
          # Display settings
          config_timezone: America/Los_Angeles
          config_display: large
          
          # Optimizations
          optimize: css,xml
          
          # Template and theming
          template: classic
          
          # Additional features
          plugin_licenses: yes
          plugin_traffic: yes
          
          # Community and social
          plugin_reactions: yes
          
          # Advanced features
          plugin_notable: yes
          plugin_notable_repositories: starred
          
          # System information (removed as it's not a valid plugin)
          