name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: '0 0 * * *'}]
  # Manual trigger
  workflow_dispatch:
  # Run on push to main
  push: {branches: [main, master]}

jobs:
  github-metrics:
    name: GitHub Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Authentication token (required)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Base metrics
          base: header, repositories
          base_indepth: yes
          
          # Language stats
          plugin_languages: yes
          plugin_languages_ignored: html,css,less,scss,sass
          plugin_languages_skipped: _test_,tests
          plugin_languages_indepth: yes
          plugin_languages_details: lines,bytes-size
          
          # GitHub calendar
          plugin_calendar: yes
          
          # Stargazers
          plugin_stargazers: yes
          
          # Output filename
          filename: metrics.base.svg
          
          # Configuration
          config_timezone: America/Los_Angeles
