name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: '0 0 * * *'}]
  # Manual trigger
  workflow_dispatch:
  # Run on push to main
  push: {branches: [main, master]}

jobs:
  github-metrics:
    name: GitHub Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Authentication token (required)
          token: ${{ secrets.METRICS_TOKEN }}
          # Your GitHub username
          user: markobonna
          
          # Base metrics
          base: header, repositories
          base_indepth: true
          
          # Plugins
          plugin_languages: yes
          plugin_languages_ignored: html,css,scss,less
          plugin_languages_skipped: _test_,tests
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          
          plugin_calendar: yes
          plugin_calendar_weeks: 12
          plugin_calendar_contributions: yes
          
          plugin_stargazers: yes
          plugin_stargazers_limit: 8
          
          plugin_followup: yes
          plugin_followup_indepth: yes
          
          # RSS Feed (optional)
          plugin_rss: yes
          plugin_rss_limit: 5
          plugin_rss_url: https://dev.to/feed/
          
          # Output settings
          filename: metrics.base.svg
          
          # Configuration
          config_timezone: America/Los_Angeles
          config_order: base.header, base.repositories, calendar, languages, stargazers, followup, rss
