name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each push (optional)
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    name: GitHub Metrics
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: markobonna
          template: classic
          base: ""
          config_timezone: America/Los_Angeles
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 7
          plugin_activity_filter: all
          plugin_calendar: yes
          plugin_calendar_weeks: 12
          plugin_calendar_contributions: yes
          plugin_contributors: yes
          plugin_contributors_sort: commits,desc
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sort: size
          plugin_followup_visibility: public
          plugin_isometric: yes
          plugin_isometric_commit: 10
          plugin_languages: yes
          plugin_languages_ignored: html,css,scss,less
          plugin_languages_skipped: _test_,tests
          plugin_people: yes
          plugin_rss: yes
          plugin_rss_limit: 5
          plugin_rss_url: https://dev.to/feed/
          plugin_screenshots: yes
          plugin_screenshots_repositories: markobonna/markobonna
          plugin_screenshots_align: center
          plugin_stargazers: yes
          plugin_stargazers_limit: 8
          plugin_stargazers_sponsor: https://github.com/sponsors/markobonna
          plugin_traffic: yes
          plugin_traffic_days: 14
          plugin_traffic_mode: daily
          plugin_traffic_limit: 7
          plugin_traffic_columns: 1
          plugin_traffic_mode: daily
          filename: github-metrics.svg
          config_zoom: "1.5"
          config_timezone: America/Los_Angeles
