name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: '0 0 * * *'}]
  # Manual trigger
  workflow_dispatch:
  # Run on push to main
  push: {branches: [main, master]}

jobs:
  github-metrics:
    name: GitHub Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Authentication token (required)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Base metrics
          base: header, repositories
          base_indepth: yes
          
          # Language stats
          plugin_languages: yes
          plugin_languages_ignored: html,css,less,scss,sass
          plugin_languages_skipped: _test_,tests
          plugin_languages_indepth: yes
          plugin_languages_details: lines,bytes-size
          
          # Activity stats
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 30
          plugin_activity_filter: push,pull_request,issues,issue_comment,commit_comment
          
          # Follow-up on issues and PRs
          plugin_followup: yes
          plugin_followup_indepth: yes
          
          # People (followers/following)
          plugin_people: yes
          plugin_people_limit: 10
          
          # Stars and stargazers
          plugin_stars: yes
          plugin_stars_limit: 10
          plugin_stargazers: yes
          
          # Sponsors and sponsorships
          plugin_sponsors: yes
          plugin_sponsorships: yes
          
          # GitHub calendar (shows commit activity)
          plugin_calendar: yes
          
          # Repositories (includes watched and starred)
          plugin_repositories: yes
          plugin_repositories_limit: 10
          
          # Topics (for starred topics)
          plugin_topics: yes
          
          # Output filename
          filename: metrics.base.svg
          
          # Configuration
          config_timezone: America/Los_Angeles
